### ISSUE TITLE
Some problems to run pyQuirk in notebook

### ISSUE THREAD

**Issue by MaldoAlberto** [adgt/pyQuirk#6]
Using Jupyter notebook version 6.2.0, with Python 3.8 

I have problems getting Quirk inside the notebook. Also, I was checking and added swap and cswap gate for interpretation, like validation, for example: in case of swap q[0], q[0] nothing appears (if it was identity).

I attach some screenshots.

![Screenshot from 2021-03-15 20-11-24](https://user-images.githubusercontent.com/21325664/111830890-333c1b00-88b4-11eb-929c-f3a3af4f3c6f.png)
![Screenshot from 2021-03-15 20-11-11](https://user-images.githubusercontent.com/21325664/111830893-33d4b180-88b4-11eb-8975-e977147da5f1.png)
![Screenshot from 2021-03-15 20-11-05](https://user-images.githubusercontent.com/21325664/111830894-346d4800-88b4-11eb-8a3e-6107b119be55.png)
![Screenshot from 2021-03-15 20-10-59](https://user-images.githubusercontent.com/21325664/111830895-346d4800-88b4-11eb-9fbb-13e648359a56.png)
![Screenshot from 2021-03-15 20-10-51](https://user-images.githubusercontent.com/21325664/111830897-3505de80-88b4-11eb-86e9-8308f5d20dc6.png)

**Comment by amirebrahimi** [comment]
Thanks. Will try and reproduce.

**Comment by amirebrahimi** [comment]
This should be fixed now with #7. You no longer need to have a source checkout, so make a copy of the example.ipynb if you want that file and then delete the directory.

Now, just install with `pip install pyQuirk`. Make sure to have JupyterLab 3 installed. You can launched with `jupyter lab example.ipynb` or with `jupyter notebook example.ipynb`.

Re: the swap, cswap gate not producing the correct circuit -- this is a known issue. We unfortunately don't support all gates, but I'm thinking of integrating something like https://github.com/quantastica/qconvert to handle conversion properly from qasm to Quirk.
